name: Deploy Web to EC2

on:
  workflow_dispatch:

jobs:
  Deploy-EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Repo
      uses: actions/checkout@v2

    - name: Move Angular App to Root
      run: mv -f ./SpaceShare.UI/* .

    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm install --force

      #TODO: change variable depending on the environment
    - name: Substitute variables in environment file (prod)
      if: github.ref == 'refs/heads/main'
      run: |
           sed -i "s~apiUrl: '.*'~apiUrl: '${{ secrets.API_URL }}'~" environment/appsettings.ts

    - name: Substitute variables in environment file (uat)
      if: github.ref == 'refs/heads/uat'
      run: |
           sed -i "s~apiUrl: '.*'~apiUrl: '${{ secrets.UAT_API_URL }}'~" environment/appsettings.ts

    - name: Substitute variables in environment file (dev)
      if: github.ref == 'refs/heads/development'
      run: |
           sed -i "s~apiUrl: '.*'~apiUrl: '${{ secrets.DEV_API_URL }}'~" environment/appsettings.ts

    - name: Build Angular Project
      run: CI=false npm run build

    - name: Verify Build Directory
      run: ls -al dist/space-share.ui

    - name: Transfer Build Folder to EC2 Instance (main)
      if: github.ref == 'refs/heads/main'
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.AWS_DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.AWS_DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.AWS_DEPLOY_PORT }}
        SOURCE: "dist/space-share.ui/"
        TARGET: ${{ secrets.AWS_DEPLOY_TARGET }}

    - name: Transfer Build Folder to EC2 Instance (uat)
      if: github.ref == 'refs/heads/uat'
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_UAT_DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.AWS_UAT_DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.AWS_UAT_DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.AWS_UAT_DEPLOY_PORT }}
        SOURCE: "dist/space-share.ui/"
        TARGET: ${{ secrets.AWS_UAT_DEPLOY_TARGET }}

    - name: Transfer Build Folder to EC2 Instance (dev)
      if: github.ref == 'refs/heads/development'
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_DEV_DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.AWS_DEV_DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.AWS_DEV_DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.AWS_DEV_DEPLOY_PORT }}
        SOURCE: "dist/space-share.ui/"
        TARGET: ${{ secrets.AWS_DEV_DEPLOY_TARGET }}
