
name: Deploy API to EC2

on:
  workflow_dispatch:

jobs:
  Deploy-EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Repo
      uses: actions/checkout@v2

    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm install
      working-directory: ./SpaceShare.API

    - name: Build Nest API
      run: npm run build
      working-directory: ./SpaceShare.API

    - name: Verify Build Directory
      run: ls -al ./SpaceShare.API/dist

    - name: Create Deployment Package
      run: tar -czf deploy-package.tar.gz -C ./SpaceShare.API dist node_modules

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key

    - name: Transfer Deployment Package to EC2 Instance
      run: |
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -P ${{ secrets.AWS_DEPLOY_PORT }} deploy-package.tar.gz ${{ secrets.AWS_DEPLOY_USER }}@${{ secrets.AWS_DEPLOY_HOST }}:${{ secrets.AWS_DEPLOY_TARGET }}/api

    - name: Extract Deployment Package on EC2
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p ${{ secrets.AWS_DEPLOY_PORT }} ${{ secrets.AWS_DEPLOY_USER }}@${{ secrets.AWS_DEPLOY_HOST }} 'tar -xzf ${{ secrets.AWS_DEPLOY_TARGET }}/api/deploy-package.tar.gz -C ${{ secrets.AWS_DEPLOY_TARGET }}/api'

    - name: Restart PM2 on EC2 Instance
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p ${{ secrets.AWS_DEPLOY_PORT }} ${{ secrets.AWS_DEPLOY_USER }}@${{ secrets.AWS_DEPLOY_HOST }} 'pm2 restart SpaceShare.Api'

