name: Deploy API to EC2

on:
  workflow_dispatch:

jobs:
  Deploy-EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Repo
      uses: actions/checkout@v2

    - name: Move to Nest API
      run: cd SpaceShare.API

    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm install
      working-directory: ./SpaceShare.API
      
    - name: Build Nest API
      run: npm run build
      working-directory: ./SpaceShare.API

    - name: Verify Build Directory
      run: ls -al ./SpaceShare.API/dist

    - name: Transfer Build Folder to EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.AWS_DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.AWS_DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.AWS_DEPLOY_PORT }}
        SOURCE: |
          ./SpaceShare.API/dist/
          ./SpaceShare.API/node_modules/ 
        TARGET: ${{ secrets.AWS_DEPLOY_TARGET }}/api
